version: '3.8'

services:
  exam-web:
    image: mycompanyname/exam-web:latest
    container_name: exam-web
    hostname: exam-web
    build:
      context: ../../
      dockerfile: src/Exam.Web/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=80086731-2876-4b83-860a-cdca3d722d2f
      - App__SelfUrl=https://localhost:44353
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://exam-web
      - App__HealthCheckUrl=http://exam-web/health-status      
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Exam;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44353:443"
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  

  
  db-migrator:
    image: mycompanyname/exam-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Exam.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__Exam_Web__RootUrl=https://localhost:44353
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Exam;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  sqldata:
    name: exam_sqldata
networks:
  abp-network:
    name: exam-network
    driver: bridge